---
# playbooks file for golang install

- name: Test Create dirs
  hosts: server-a
  tasks:
    - name: create dir tag simba
      file:
        path: /usr/simba
        state: directory
        owner: root
        group: root
        mode: 0644
      tags: [simba]
    - name: create dir tag alluka
      file:
        path: /usr/alluka
        state: directory
        owner: root
        group: root
        mode: 0644
      tags: [alluka]
    - name: create dir tag cerberus
      file:
        path: /usr/cerberus
        state: directory
        owner: root
        group: root
        mode: 0644
      tags: [cerberus]
    - name: create dir tag astro
      file:
        path: /usr/astro
        state: directory
        owner: root
        group: root
        mode: 0644
      tags: [astro]
    - name: create dir tag anbu
      file:
        path: /usr/anbu
        state: directory
        owner: root
        group: root
        mode: 0644
      tags: [anbu]
