---
# playbooks file for golang install

- name: Test Create dirs
  hosts: server-a
  default:
    default_nama_tim: astro2
  tasks:
    - name: create dir
      file:
        path: '/usr/{{ nama_tim | default(default_nama_tim) }}'
        state: directory
        owner: root
        group: root
        mode: 0644