---
# playbooks file for golang install

- name: Test Create dirs
  hosts: server-a
  vars_files:
    - vars/main.yml
  tasks:
    - name: create dir
      file:
        path: '/usr/{{ nama_tim | default(default_nama_tim) }}'
        state: directory
        owner: root
        group: root
        mode: 0644
      register: risk_demo
      tags: harus
    - name: create dir 2
      file:
        path: '/usr/{{ nama_tim2 | default(default_nama_tim) }}'
        state: directory
        owner: root
        group: root
        mode: 0644
      when: risk_demo
      tags: always