---
# handlers file for golang-service-deploy
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes
  listen:
    - "rsmn-demo project file updated"

- name: restart rsmn-demo
  systemd:
    name: rsmn-demo
    enabled: yes
    state: restarted
  become: yes
  listen:
    - "rsmn-demo system config updated"