---
# tasks file for golang-service-deploy
- name: create dir
  file:
    path: '{{ golang_service_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0644
- name: pull code repo
  git:
    repo: '{{ golang_service_repo }}'
    dest: '{{ golang_service_dir }}'
  notify:
    - "rsmn-demo project file updated"
- name: build go project
  shell: '({{ golang_service_dir }} && go build -o rsmn-demo)'
- name: copy systemd config file
  copy:
    src: rsmn-demo.service
    dest: '{{ systemd_service_config_dir }}'
    owner: root
    group: root
    mode: 0644