---
# tasks file for golang-service-deploy
- name: create dir
  file:
    path: /usr/github.com/risk-tech-ansible-server-demo
    state: directory
    owner: root
    group: root
    mode: 0644
- name: pull code repo
  git:
    repo: https://github.com/IshlahulHanif/risk-tech-ansible-server-demo.git
    dest: /usr/github.com/risk-tech-ansible-server-demo
  notify:
    - "rsmn-demo project file updated"
- name: build go project
  shell: (cd /usr/github.com/risk-tech-ansible-server-demo && go build -o rsmn-demo)
- name: copy systemd config file
  copy:
    src: rsmn-demo.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0644