---
# tasks file for golang-service-deploy
- name: copy systemd config file
  copy:
    src: rsmn-demo.service
    dest: '{{ default_systemd_service_config_dir }}'
    owner: root
    group: root
    mode: 0644
  notify:
    - "rsmn-demo system config updated"
- name: create dir
  file:
    path: '{{ golang_service_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0644
  register: dir_created
- name: pull code repo
  git:
    repo: '{{ golang_service_repo }}'
    dest: '{{ golang_service_dir }}'
  register: code_updated
  when: dir_created.changed
- name: build go project
  shell: '(cd {{ golang_service_dir }} && go build -o rsmn-demo)'
  notify:
    - "rsmn-demo project built"